import {RedLight} from "../assets/styles/GlobalStyle";

export const galleryOptions = {
    enableRotationGesture: true,
    hideBottomControls: true,
    cropperActiveWidgetColor: 'red',
    cropperCancelText: "بستن",
    cropperChooseText: "انتخاب",
    cropperToolbarTitle: "برش تصویر",
    cropperToolbarColor: RedLight,
    cropperStatusBarColor: RedLight,
    cropperTintColor: 'red',
    loadingLabelText: "لطفا صبر کنید",
    compressImageQuality: .9,
    multiple: false,
    cropping: true,
    includeBase64: true,
    compressImageMaxHeight: 750,
    compressImageMaxWidth: 750,
    width: 750,
    height: 750,
    forceJpg: true,
    mediaType: "photo",
}
export const cameraOptions=  {
    enableRotationGesture: true,
    hideBottomControls: true,
    cropperActiveWidgetColor: 'red',
    cropperCancelText: "بستن",
    cropperChooseText: "انتخاب",
    cropperToolbarTitle: "برش تصویر",
    cropperToolbarColor: RedLight,
    cropperStatusBarColor: RedLight,
    cropperTintColor: 'red',
    loadingLabelText: "لطفا صبر کنید",
    compressImageQuality: .85,
    cropping: true,
    includeBase64: true,
    compressImageMaxHeight: 750,
    compressImageMaxWidth: 750,
    width: 750,
    height: 750,
    forceJpg: true,
    mediaType: "photo",
}